version: 1.0.{build}

branches:
  only:
    - master

os: Visual Studio 2017
test: off

environment:
  access_token:
    secure: ZVCctXLgOwGK52cn0/a+kpBGRsyedySv7bV3o1N8tZ4THyhsG+X/HJSik8QNtDDv

build_script:
  - install-pretzel.cmd
  - bake-full.cmd

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.name "Andrey Akinshin"
  - git config --global user.email andrey.akinshin@gmail.com
  - deploy.cmd